---
- include_tasks: setup-Debian.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- name: Ensure docker service is started
  service:
    name: docker
    state: started
    enabled: true