---
- name: CentOS | Ensure old versions of Docker are not installed
  ansible.builtin.package:
    name: '{{ docker_yum_deprecated_packages }}'
    state: absent

- name: CentOS | Ensure dependencies are installed
  ansible.builtin.package:
    name: '{{ docker_yum_required_packages }}'
    state: present
    update_cache: true

- name: CentOS | Ensure docker repository added
  get_url:
    url: "{{ docker_yum_repository }}"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: CentOS | Ensure docker packages are installed
  ansible.builtin.package:
    name: '{{ docker_packages }}'
    state: present
    update_cache: true
  notify: "Add user(s) to docker group"
