---
- name: Debian OS | Ensure old versions of Docker are not installed
  ansible.builtin.package:
    name: '{{ docker_apt_deprecated_packages }}'
    state: absent
    purge: true


- name: Debian OS | Ensure dependencies are installed
  ansible.builtin.package:
    name: '{{ docker_apt_required_packages }}'
    state: present
    update_cache: true

- name: Debian OS | Ensure docker GPG key added
  ansible.builtin.apt_key:
    url: '{{ docker_base_url }}/gpg'
    state: present

- name: Debian OS | Ensure docker repository added
  ansible.builtin.apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: present
    mode: 0644

- name: Debian OS | Ensure docker packages are installed
  ansible.builtin.package:
    name: '{{ docker_packages }}'
    state: present
    update_cache: true
  notify: "Add user(s) to docker group"
